In [1]:
import pandas as pd
df = pd.read_csv("heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [2]:
import numpy as np
import scipy.stats as stats

numeric_cols = df.select_dtypes(include=[float, int]).columns # Select numaric variables

df_zscore = df.copy()
df_zscore[numeric_cols] = df[numeric_cols].apply(stats.zscore)

df_zscore.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,-1.433140,M,ATA,0.410909,0.825070,-0.551341,Normal,1.382928,N,-0.832432,Up,-1.113115
1,-0.478484,F,NAP,1.491752,-0.171961,-0.551341,Normal,0.754157,N,0.105664,Flat,0.898380
2,-1.751359,M,ATA,-0.129513,0.770188,-0.551341,ST,-1.525138,N,-0.832432,Up,-1.113115
3,-0.584556,F,ASY,0.302825,0.139040,-0.551341,Normal,-1.132156,Y,0.574711,Flat,0.898380
4,0.051881,M,NAP,0.951331,-0.034755,-0.551341,Normal,-0.581981,N,-0.832432,Up,-1.113115

In [3]:
# Remove outlires
df_no_outliers = df[(df_zscore[numeric_cols] < 3).all(axis=1) & (df_zscore[numeric_cols] > -3).all(axis=1)]
df_no_outliers

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_no_outliers['Sex'] = le.fit_transform(df_no_outliers['Sex'])
df_no_outliers['ChestPainType'] = le.fit_transform(df_no_outliers['ChestPainType'])
df_no_outliers['RestingECG'] = le.fit_transform(df_no_outliers['RestingECG'])
df_no_outliers['ExerciseAngina'] = le.fit_transform(df_no_outliers['ExerciseAngina'])
df_no_outliers['ST_Slope'] = le.fit_transform(df_no_outliers['ST_Slope'])
df_no_outliers

C:\Users\21061\AppData\Local\Temp\ipykernel_21356\2067451741.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['Sex'] = le.fit_transform(df_no_outliers['Sex'])
C:\Users\21061\AppData\Local\Temp\ipykernel_21356\2067451741.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['ChestPainType'] = le.fit_transform(df_no_outliers['ChestPainType'])
C:\Users\21061\AppData\Local\Temp\ipykernel_21356\2067451741.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['RestingECG'] = le.fit_transform(df_no_outliers['RestingECG'])
C:\Users\21061\AppData\Local\Temp\ipykernel_21356\2067451741.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['ExerciseAngina'] = le.fit_transform(df_no_outliers['ExerciseAngina'])
C:\Users\21061\AppData\Local\Temp\ipykernel_21356\2067451741.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers['ST_Slope'] = le.fit_transform(df_no_outliers['ST_Slope'])

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1
914,68,1,0,144,193,1,1,141,0,3.4,1,1
915,57,1,0,130,131,0,1,115,1,1.2,1,1
916,57,0,1,130,236,0,0,174,0,0.0,1,1
917,38,1,2,138,175,0,1,173,0,0.0,2,0

In [17]:
X = df_no_outliers.drop("HeartDisease", axis='columns')
y = df_no_outliers.HeartDisease

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:3]

array([[-1.42815446,  0.515943  ,  0.2245723 ,  0.46590022,  0.84963584,
        -0.5503622 ,  0.01414258,  1.38431998, -0.8229452 , -0.85546862,
         1.04249607],
       [-0.47585532, -1.93819859,  1.27063705,  1.63471366, -0.16812204,
        -0.5503622 ,  0.01414258,  0.7529728 , -0.8229452 ,  0.13751561,
        -0.62216462],
       [-1.7455875 ,  0.515943  ,  0.2245723 , -0.1185065 ,  0.79361247,
        -0.5503622 ,  1.60341473, -1.53566071, -0.8229452 , -0.85546862,
         1.04249607]])

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=20)

In [33]:
from sklearn.svm import SVC
model = SVC()

In [36]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

scores = cross_val_score(SVC(), X, y, cv=5)
scores.mean()

np.float64(0.6884667908131595)

In [37]:
model.fit(X_train, y_train)

SVC()

In [38]:
model.score(X_test, y_test)

0.9

In [39]:

from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(
    estimator = SVC(), 
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
bag_model.fit(X_train, y_train)
bag_model.oob_score_

0.8595271210013908

In [40]:
bag_model.score(X_test, y_test)

0.9055555555555556

In [41]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

scores = cross_val_score(DecisionTreeClassifier(), X, y, cv=5)
scores

array([0.80555556, 0.75      , 0.77222222, 0.75555556, 0.62569832])

In [42]:
scores.mean()

np.float64(0.741806331471136)

In [47]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.9, 
    oob_score=True,
    random_state=0
)
bag_model.fit(X_train, y_train)
bag_model.oob_score_

0.8386648122392212

In [48]:
bag_model.score(X_test, y_test)

0.9166666666666666

In [49]:
bag_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.9, 
    oob_score=True,
    random_state=0
)
scores = cross_val_score(bag_model, X, y, cv=5)
scores

array([0.89444444, 0.79444444, 0.83333333, 0.81111111, 0.72067039])

In [50]:
scores.mean()

np.float64(0.8108007448789571)

In [51]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(), X, y, cv=5)
scores.mean()

np.float64(0.8197454996896338)